# Generated by Django 3.1.3 on 2020-11-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedata',
            name='duration',
        ),
        migrations.AddField(
            model_name='moviedata',
            name='movie_type',
            field=models.CharField(choices=[('ACTION', 'ACTION'), ('COMEDY', 'COMEDY'), ('HORROR', 'HORROR'), ('ADVENTURE', 'ADVENTURE'), ('DRAMA', 'DRAMA'), ('CRIME', 'CRIME')], default='ACTION', max_length=255),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='runtime',
            field=models.IntegerField(default=3, max_length=2),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='ratings',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
