# Generated by Django 3.1.3 on 2020-11-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedata', '0002_auto_20201107_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
